-- team 데이터 추가
INSERT INTO DELIVERY (ADDRESS, STATUS) VALUES ('서울시 강남구', 'READY');
INSERT INTO DELIVERY (ADDRESS, STATUS) VALUES ('서울시 서초구', 'SHIPPED');
-- member 데이터 추가
INSERT INTO ORDER (NAME, DELIVERY_ID) VALUES ('ORD-001', 1);
INSERT INTO ORDER (NAME_NUMBER, DELIVERY_ID) VALUES ('ORD-002', 2);

INSERT INTO PRODUCT (NAME, PRICE, ORDER_ID) VALUES ('노트북', 1500000, 1);
INSERT INTO PRODUCT (NAME, PRICE, ORDER_ID) VALUES ('마우스', 50000, 1);
INSERT INTO PRODUCT (NAME, PRICE, ORDER_ID) VALUES ('모니터', 300000, 2);
INSERT INTO PRODUCT (NAME, PRICE, ORDER_ID) VALUES ('키보드', 80000, 2);